# На каком порту стартует приложение
server:
    port: 8083

# Настройки логирования
logging:
    level:
        com.example.demo: debug
    file:
        name: logs/prod.log

# Настройки БД
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://database:5432/converter_prod
        username: admin_prod
        password: 456
    jpa:
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml
